version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: llamaindex-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - llamaindex_pgdata:/var/lib/postgresql/data

volumes:
  llamaindex_pgdata:
