version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: llamaindex-postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - llamaindex_pgdata:/var/lib/postgresql/data

volumes:
  llamaindex_pgdata:
